---
  title: "Plots for figure 2"
output: html_document
---
###read in data
```{r include=F, message=F,echo=F,warning=F,results='hide'}
subjs=read.csv('data/NYU_meta.csv',header=T,stringsAsFactors = F,check.names=F)

##keep only stage I
subjs=subjs[subjs$stage %in% c('IA','IB','1'),]  #150 to 145 patients
nyu=data.frame(subjs=subjs$Study_ID,subtype=subjs$ProgType,time=as.numeric(subjs$`Time to Recurrence`),status=subjs$Progression,stringsAsFactors = F)

sex=rep('Male',nrow(subjs))
sex[subjs$Male_1==2]='Female'
data=data.frame(subjs,
                followup=as.numeric(subjs$`Time to Recurrence`),histology=subjs$Histologic_component_of_hot_spot_of_nuclear_atypia,
                match_normal=subjs$match_normal,stringsAsFactors = F)
data$Race[data$Race=='white']='White'
data$Race[data$Race=='Hipanic or Latino']='Hispanic'
data$Race[data$Race=='asian']='Asian'
data$Race[data$Race=='Black or African America']='Black'
data$Race=factor(data$Race,levels=c('White','Asian','Black','Hispanic'))

data$LVI=factor(data$LVI,levels=c(0,1),labels=c('No','Yes'))

data$Pleural_Invasion=factor(data$Pleural_Invasion,levels=c(0,1),labels=c('No','Yes'))

data$Sex=factor(data$Male_1,levels=c(2,1),labels=c('Female','Male'))
data$nuclear_histology=data$Histologic_component_of_hot_spot_of_nuclear_atypia
data$nuclear_histology[data$nuclear_histology=='n.a']='Unknown'

data$LepidicPerc=as.numeric(data$LepidicPerc)
data$MicropapillaryPerc=as.numeric(data$MicropapillaryPerc)
data$Necrosis_Perc=as.numeric(data$Necrosis_Perc)
data$Nuclear_grade=as.numeric(data$Nuclear_grade)
data$smoking_Pack_Years=as.numeric(data$smoking_Pack_Years)
data$PapillaryPerc=as.numeric(data$PapillaryPerc)
data$SolidPerc=as.numeric(data$SolidPerc)
data$AcinarPerc=as.numeric(data$AcinarPerc)
data$CribriformPerc=as.numeric(data$CribriformPerc)
data$Fused_glandsPerc=as.numeric(data$Fused_glandsPerc)
data$Cytologic_grade[data$Cytologic_grade=='n.a']=NaN
data$Cytologic_grade=factor(data$Cytologic_grade,levels=c('Low','High'))
data$nuclear_histology=factor(data$nuclear_histology,levels=c( 'Unknown',"Fused glands", "Micropapillary", "Solid", "Papillary", "Acinar" , "Cribriform","Lepidic"  ))
features=c('Progression','Time.to.Recurrence','Race','Sex','Age','smoking_Pack_Years','Cytologic_grade','Size_cm','LVI','Pleural_Invasion','AcinarPerc','LepidicPerc','MicropapillaryPerc','Necrosis_Perc',
           'PapillaryPerc','SolidPerc','CribriformPerc','Fused_glandsPerc','Nuclear_grade')
data=data[data$match_normal,features]##only doing with matched normal
clinics=data
names(data)[1]='Recur'
data[data==-9]=0

###get figure 2 roc curve data

varcut=200
datamod='normalized'
datasubset='matched_rm5years'
subset='12vs0'
datatypes=c('tumor','control')
fold=10
ind_censor=1
ind_time=2
subjs=read.csv('data/NYU_meta.csv',header=T,stringsAsFactors = F)

pred_data=list()
for (i in 1:length(datatypes)) {
  datatype=datatypes[i]
  temp=read.csv(paste0('data/models/',datamod,'_',datasubset,'_',datatype,'_fpkm_',subset,'_glm_v',varcut,'_pred_prob.csv'),stringsAsFactors = F,check.names=F)
  temp=temp[temp$bootid==1,]
  set.seed(1)
  curind=match(temp$subj,subjs$Study_ID)
  temp$Progression=as.numeric(subjs$Progression[curind])
  temp$TTP=as.numeric(subjs$Time.to.Recurrence[curind])
  pred_data[[i]]=temp}
```


```{r include=F, message=F,echo=F,warning=F,results='hide'}
outpath='figure2'
if (!dir.exists(outpath))
  dir.create(outpath,recursive = T)
varcut=200
datamod='normalized'
datasubset='matched_rm5years'
subset='12vs0'
datatypes=c('tumor','control')
fold=10
ind_censor=1
ind_time=2

auc_labels=c('AUC = 0.63 (0.53~0.72)','AUC = 0.83 (0.74~0.92)')
for (i in 1:length(datatypes)) {
  datatype=datatypes[i]
  auc_label=auc_labels[i]
  temp=pred_data[[i]]
  
  roc.list=roc(temp$Progression,temp$prob,smooth=F,thresholds=30)
  if (roc.list$auc<0.5)
    temp$prob=1-temp$prob
  roc.list=roc(temp$Progression,temp$prob,smooth=F,thresholds=30)
  ciobj <- ci.se(roc.list, specificities=seq(0, 1, l=25))
  dat.ci <- data.frame(x = as.numeric(rownames(ciobj)),
                       lower = ciobj[, 1],
                       upper = ciobj[, 3])
  roclist=list()
  roclist[[auc_label]]=roc.list
  p1=ggroc(roclist,color='blue',size=1.1,aes=c('linetype')) +
    geom_abline(slope=1, intercept = 1, linetype = "dashed", alpha=0.7, color = "red") + 
    geom_ribbon(data = dat.ci, aes(x = x, ymin = lower, ymax = upper), fill = "grey", alpha= 0.2, inherit.aes = F) +
    labs(x='Specificity',y='Sensitivity',linetype='auc')+
    theme(panel.border = element_rect(fill=NA,color="black", size=1.0, linetype="solid"),
          panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
          axis.text=element_text(size=20),
          axis.title=element_text(size=20),
          panel.background = element_blank(),
          legend.position =c(.6,.1),
          legend.title = element_blank(),
          legend.text = element_text(size=20))+
    coord_equal()
  filename=paste(outpath,'/figure2ef_roc_',datatype,'_',subset,'.png',collapse='',sep='')
  ggsave(filename = filename,p1,device='png',width=8,height=6)
}


###supp figure 2 forest plot of hazard ratio on clinical data
ind_time=2
res=data.frame(matrix(NaN,0,5))
names(res)=c('var','sub_var','N','Hazard_Ratio','Pvalue')
features=names(data)[-c(1:2)]

for (i in 1:length(features)) {
  
  model_formula=as.formula(paste(paste('Surv(', names(data)[ind_time],',Recur) ~',sep=''),
                                 paste(features[i],collapse="+")))
  
  surv_fit1=coxph(as.formula(model_formula),data)
  coef=summary(surv_fit1)$coefficients
  
  curres=data.frame(matrix(NaN,20,5))
  names(curres)=c('var','sub_var','N','Hazard_Ratio','Pvalue')
  if (class(data[,features[i]])=='factor') {
    curres[1,1]=features[i]
    curres[1,2]=levels(data[,features[i]])[1]
    curres[1,3]=sum(data[,features[i]]==levels(data[,features[i]])[1],na.rm=T)
    curres[1,4]='reference'
    for (j in 1:(length(levels(data[,features[i]]))-1)) {
      if (is.na(coef[j,1])) {
        coef[j,1]=0
        coef[j,3]=10
        coef[j,5]=1.0}
      if (abs(coef[j,3]/coef[j,1]) >10)  {  ####manually correct large standard error
        coef[j,1]=coef[j,1]/coef[j,3]
        coef[j,3]=coef[j,3]/coef[j,3]
      }
      curres[j+1,1]=features[i]
      curres[j+1,2]=gsub(features[i],'',rownames(coef)[j])
      curres[j+1,3]=sum(data[,features[i]]==levels(data[,features[i]])[j+1],na.rm=T)
      curres[j+1,4]=sprintf('%.2f (%.2f~%.2f)',(coef[j,1]),(coef[j,1]-1.96*coef[j,3]),(coef[j,1]+1.96*coef[j,3]))
      curres[j+1,5]=coef[j,5]
    } 
    
  } else {
    for (j in 1:1) {
      if (is.na(coef[j,1])) {
        coef[j,1]=0
        coef[j,3]=10
        coef[j,5]=1.0}
      if (abs(coef[j,2]/coef[j,1]) >10 || coef[j,1]>13)  {  #### correction for large standard error
        coef[j,1]=coef[j,1]/coef[j,3]
        coef[j,3]=coef[j,3]/coef[j,3]
      }
      curres[j,1]=features[i]
      curres[j,2]=features[i]
      curres[j,3]=nrow(data)
      curres[j,4]=sprintf('%.2f (%.2f~%.2f)',(coef[j,1]),(coef[j,1]-1.96*coef[j,3]),(coef[j,1]+1.96*coef[j,3]))
      curres[j,5]=coef[j,5] }
  }
  res=rbind.data.frame(res,curres)
  
}

res=res[!is.na(res[,1]) & res[,1]!='NaN',]


###plottting forest
maxval=5
temp=res
data=data.frame(matrix(NaN,50,7))
names(data)=c('Variable','N','AUC','CI_low','CI_high','','P')
vars=unique(temp$var)
cnt=0
for (i in 1:length(vars)) {
  cnt=cnt+1
  if (sum(temp$var==vars[i])>1) {
    data[cnt,1]=vars[i]
    data[cnt,2:7]=NA
    ind=which(temp$var==vars[i])
    for (j in ind) {
      cnt=cnt+1
      data[cnt,1]=temp$sub_var[j]
      data[cnt,2]=temp$N[j]
      
      if (temp$Hazard_Ratio[j]=='reference') {
        data[cnt,3:5]=0.0
        data[cnt,7]=NA} else {
          data[cnt,3]=as.numeric(strsplit(temp[j,4],' ')[[1]][1])
          tt1=gsub('[(|)]','',strsplit(temp[j,4],' ')[[1]][2])
          data[cnt,4]=as.numeric(strsplit(tt1,'~')[[1]][1])
          data[cnt,5]=as.numeric(strsplit(tt1,'~')[[1]][2])
        }
      data[cnt,6]=temp$Hazard_Ratio[j]
      if (data[cnt,5]>maxval) {
        data[cnt,5]=maxval
        data[cnt,6]=paste0(strsplit(temp$Hazard_Ratio[j],'~')[[1]][1],'~200)') 
        
        data[cnt,6]=paste0(maxval,strsplit(data[cnt,6],' ')[[1]][2]) 
      }
      data[cnt,7]=sprintf('%.3f',round(  temp$Pvalue[j],3))  
    } } else {
      ind=temp$var==vars[i]
      data[cnt,1]=vars[i]
      data[cnt,2]=temp$N[ind]
      data[cnt,3]=as.numeric(strsplit(temp[ind,4],' ')[[1]][1])
      tt1=gsub('[(|)]','',strsplit(temp[ind,4],' ')[[1]][2])
      data[cnt,4]=as.numeric(strsplit(tt1,'~')[[1]][1])
      data[cnt,5]=as.numeric(strsplit(tt1,'~')[[1]][2])
      data[cnt,6]=temp$Hazard_Ratio[ind]
      if (data[cnt,5]>maxval) {
        data[cnt,5]=maxval
        data[cnt,6]=paste0(strsplit(temp$Hazard_Ratio[ind],'~')[[1]][1],'~200)') }
      data[cnt,7]=sprintf('%.3f',round( temp$Pvalue[ind],3)) 
    }
}
data=data[data[,1]!='NaN',] 
data$CI_high[is.infinite(data$CI_high) || data$CI_high>maxval]=maxval

data$AUC[data$AUC>maxval]=maxval/2.0
for (i in 1:nrow(data)) {
  if (!is.na(data[i,6]) & data[i,6]=='reference')
    data[i,7]=NA }
row_names=list(as.list(c('Variable',data$Variable)),as.list(c('N',data$N)),as.list(c('',data[,6])),as.list(c('P',data$P)))
data=rbind.data.frame(rep(NA,1,7),data)

pdf( paste('figure2/supp_fig2_log_Hazard_Ratio.pdf',sep=''),width=10,height=14)
own <- fpTxtGp(label = gpar(fontfamily = "ArialMT",cex=1.2),ticks = gpar(cex=1.0),xlab=gpar(cex=1.8))
ticks <- seq(-5,5, 1)
ticks=c(-5, -3, -1,  0,1,  3,  5)
lab <- sapply((-1):3, function(i) as.expression(bquote(10^ .(i))))
forestplot(labeltext=row_names,graph.pos=3,
           data[,c("AUC", "CI_low", "CI_high")],
           zero = 0,
           cex  = 2.2,
           lwd.ci=2,
           xlog=0,
           txt_gp = own,
           col=fpColors(box=c("black", "gold"),
                        line=c("black", "orange"),
                        summary=c("darkblue", "red")),
           lineheight = "auto",
           boxsize=0.45,
           xlab = "log (Hazard Ratio)",
           xticks=ticks,
           new_page = FALSE)

dev.off()
```

