---
title: "Figure 5: Association of module scores in normal tissue with different variables - Dot plot of c-index values across modules and TCGA cohorts"
output: html_notebook
---

```{r message=FALSE, warning=FALSE}
suppressPackageStartupMessages({
  library(dplyr)
  library(openxlsx)
  library(stringr)
  library(matrixStats)
  library(tidyr)
  library(readr)
  library(ggrepel)
  library(ggtext)
})
```

```{r}
results_tab <- read.xlsx("/gpfs/data/tsirigoslab/home/leh06/Others/NYU_RNA/surv_stats_nyustage1modules_on_tcga_norm_v5.xlsx")
results_tab <- results_tab[(results_tab$stage == "all_stages") & (results_tab$tissue_type == "normal") & (! results_tab$cohort %in% c("LUAD", "LUSC", "KICH", "KIRP",
                                                                                                                                      "COAD", "PRAD", "Kidney", "LIHC",
                                                                                                                                      "THCA")) &
                             (!is.na(results_tab$c_index)), ]
results_tab <- results_tab[order(results_tab$c_index),]
results_tab$c_index_ranks <- order(results_tab$c_index)

# Reverse all c-indexes
results_tab$c_index <- 1 - results_tab$c_index

results_tab$Cohort <- results_tab$cohort

results_tab$cohort <- str_replace_all(results_tab$cohort, "BRCA", "Breast")
results_tab$cohort <- str_replace_all(results_tab$cohort, "KIRC", "Kidney")
results_tab$cohort <- str_replace_all(results_tab$cohort, "HNSC", "Head</b></span><br><span style='font-size: 45pt'><b>and</b></span><br><span style='font-size: 45pt'><b>Neck")
results_tab$cohort <- str_replace_all(results_tab$cohort, "LUNG", "Lung")
# results_tab$cohort <- str_replace_all(results_tab$cohort, "THCA", "Thyroid")
# results_tab$cohort <- str_replace_all(results_tab$cohort, "LIHC", "Liver")

# results_tab$labels <- results_tab$module
# results_tab$labels[results_tab$module == "20"] <- paste0("module-20/",results_tab[results_tab$module == "20","cohort"])
# results_tab$labels[results_tab$module != "20"] <- ""

results_tab$module <- as.integer(results_tab$module)

# write.xlsx(results_tab[,! names(results_tab) %in% c("c_index_ranks", "labels")],paste0("/gpfs/data/tsirigoslab/home/leh06/Others/NYU_RNA/surv_stats_tcga_modules_filtered_v3.xlsx"))

results_tab$cohort_label <- paste0("<span style='font-size: 45pt'><b>", results_tab$cohort, "</b></span><br><span style='font-size: 45pt'>n = ", results_tab$nb_samples, "</span>")

results_tab
```


A dot plot as follows:
- rows = modules
- columns = cancer types
- dot size inversely proportional to c-index (low c-index = big size)
- dot color according to p-value (use the red-to-orange palette that you have used before for the Hallmarks)

```{r}
results_tab_filtered <- results_tab
results_tab_filtered$pval[results_tab$pval>0.15] <- NA

# Generate dotplot
png(file="/gpfs/data/tsirigoslab/home/leh06/Others/NYU_RNA/dotplot_tcga_c_indexes_modules_test_v2.png",  width = 35, height = 20, units = 'in', res = 300)
ggplot(results_tab_filtered, aes(x = cohort_label, 
                          y = as.factor(module), 
                          color = c_index, size=pval)) + 
  geom_point() +
  facet_grid(. ~ survival_type) +
  scale_size_continuous(range = c(30,10), breaks = c(0.025, 0.05, 0.100)) +
  labs(color = "C-index", size = "P-value") +
  theme_bw(base_rect_size = 1, base_line_size = 0.3) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        text = element_text(size = 50), legend.key.size = unit(1, 'cm'),
        axis.text.x = ggtext::element_markdown(), axis.text.y = element_text(size = 50),
        axis.title = element_text(size = 60),
        strip.text.x = element_text(size = 50, face = "bold"),
        legend.title = element_text(size=50), 
        legend.text = element_text(size=40)) +
  scale_color_gradient2(high = "red", mid = "white", low = "blue", midpoint = 0.5) +
  xlab("Cell type") +
  # ggtitle("Dotplot of c-indexes") +
  scale_y_discrete("Module", labels = as.character(results_tab_filtered$module), breaks = results_tab_filtered$module)
dev.off()
```